version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-taxi
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    expose:
      - 5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app
   



